import time
import pygame

file = open("./Rasputin.txt")
Rasputin_lyr = file.readlines()

# for i in Rasputin_lyr:
#     time.sleep(54)
#     print(Rasputin_lyr[0])

# pygame.mixer.init()
# pygame.mixer.music.load('./assets/Song.mp3')
# pygame.mixer.music.player()

# for i in Rasputin_lyr:



# def line(waitTime, lineText):
#     time.sleep(waitTime)
#     print(lineText)


for i in range(len(Rasputin_lyr)):
    print(f"line(2, Rasputin_lyr[{i}])")
line(2, Rasputin_lyr[0])
line(2, Rasputin_lyr[1])
line(2, Rasputin_lyr[2])
line(2, Rasputin_lyr[3])
line(2, Rasputin_lyr[4])
line(2, Rasputin_lyr[5])
line(2, Rasputin_lyr[6])
line(2, Rasputin_lyr[7])
line(2, Rasputin_lyr[8])
line(2, Rasputin_lyr[9])
line(2, Rasputin_lyr[10])
line(2, Rasputin_lyr[11])
line(2, Rasputin_lyr[12])
line(2, Rasputin_lyr[13])
line(2, Rasputin_lyr[14])
line(2, Rasputin_lyr[15])
line(2, Rasputin_lyr[16])
line(2, Rasputin_lyr[17])
line(2, Rasputin_lyr[18])
line(2, Rasputin_lyr[19])
line(2, Rasputin_lyr[20])
line(2, Rasputin_lyr[21])
line(2, Rasputin_lyr[22])
line(2, Rasputin_lyr[23])
line(2, Rasputin_lyr[24])
line(2, Rasputin_lyr[25])
line(2, Rasputin_lyr[26])
line(2, Rasputin_lyr[27])
line(2, Rasputin_lyr[28])
line(2, Rasputin_lyr[29])
line(2, Rasputin_lyr[30])
line(2, Rasputin_lyr[31])
line(2, Rasputin_lyr[32])
line(2, Rasputin_lyr[33])
line(2, Rasputin_lyr[34])
line(2, Rasputin_lyr[35])
line(2, Rasputin_lyr[36])
line(2, Rasputin_lyr[37])
line(2, Rasputin_lyr[38])
line(2, Rasputin_lyr[39])
line(2, Rasputin_lyr[40])
line(2, Rasputin_lyr[41])
line(2, Rasputin_lyr[42])
line(2, Rasputin_lyr[43])
line(2, Rasputin_lyr[44])
line(2, Rasputin_lyr[45])
line(2, Rasputin_lyr[46])
line(2, Rasputin_lyr[47])
line(2, Rasputin_lyr[48])
line(2, Rasputin_lyr[49])
line(2, Rasputin_lyr[50])
line(2, Rasputin_lyr[51])
line(2, Rasputin_lyr[52])
line(2, Rasputin_lyr[53])
line(2, Rasputin_lyr[54])
line(2, Rasputin_lyr[55])
line(2, Rasputin_lyr[56])
line(2, Rasputin_lyr[57])
line(2, Rasputin_lyr[58])
line(2, Rasputin_lyr[59])
line(2, Rasputin_lyr[60])
line(2, Rasputin_lyr[61])
line(2, Rasputin_lyr[62])
line(2, Rasputin_lyr[63])
line(2, Rasputin_lyr[64])
line(2, Rasputin_lyr[65])
line(2, Rasputin_lyr[66])
line(2, Rasputin_lyr[67])
line(2, Rasputin_lyr[68])
line(2, Rasputin_lyr[69])
line(2, Rasputin_lyr[70])
line(2, Rasputin_lyr[71])
line(2, Rasputin_lyr[72])
line(2, Rasputin_lyr[73])
line(2, Rasputin_lyr[74])
line(2, Rasputin_lyr[75])
line(2, Rasputin_lyr[76])
line(2, Rasputin_lyr[77])
line(2, Rasputin_lyr[78])
line(2, Rasputin_lyr[79])
line(2, Rasputin_lyr[80])
line(2, Rasputin_lyr[81])
line(2, Rasputin_lyr[82])
line(2, Rasputin_lyr[83])
line(2, Rasputin_lyr[84])
line(2, Rasputin_lyr[85])
line(2, Rasputin_lyr[86])
line(2, Rasputin_lyr[87])